// Generated by CoffeeScript 1.7.1
(function() {
  var app, async, config, env, express, fs, http, models_path, path, router, setting;

  express = require('express');

  http = require('http');

  path = require('path');

  fs = require('fs');

  async = require('async');

  env = process.env.NODE_ENV || 'development';

  config = require('./configure/config')[env];

  app = express();

  setting = require('./configure/setting')(app, config);

  models_path = config.root + '/app/model';

  fs.readdirSync(models_path).forEach(function(file) {
    return require(models_path + '/' + file);
  });

  router = require('./configure/router')(app);

  http.createServer(app).listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
