// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    getDate: function() {
      var currentDate, day, month, myDate, year;
      myDate = new Date();
      year = myDate.getFullYear();
      month = myDate.getMonth() + 1;
      day = myDate.getDate();
      month = month < 10 ? "0" + month : month;
      day = day < 10 ? "0" + day : day;
      currentDate = year + "-" + month + "-" + day;
      return currentDate;
    },
    getUniqueNum: function() {
      var day, hour, millSecond, minute, month, myDate, second, uniqueNum, year;
      myDate = new Date();
      year = myDate.getFullYear();
      month = myDate.getMonth() + 1;
      day = myDate.getDate();
      hour = myDate.getHours();
      minute = myDate.getMinutes();
      second = myDate.getSeconds();
      millSecond = myDate.getMilliseconds();
      month = month < 10 ? "0" + month : month;
      day = day < 10 ? "0" + day : day;
      hour = hour < 10 ? "0" + hour : hour;
      minute = minute < 10 ? "0" + minute : minute;
      second = second < 10 ? "0" + second : second;
      millSecond = millSecond < 100 ? (millSecond < 10 ? "00" + millSecond : "0" + millSecond) : millSecond;
      uniqueNum = year + "-" + month + "-" + day + " " + hour + ":" + minute + ":" + second;
      return uniqueNum;
    },
    getWeekAgoDate: function() {
      var getWeekAgo, occur, tday, tmonth, tyear, weekAgo;
      occur = new Date();
      weekAgo = new Date(occur.getTime() - 1000 * 60 * 60 * 24 * 7);
      tyear = weekAgo.getFullYear();
      tmonth = weekAgo.getMonth() + 1;
      tday = weekAgo.getDate();
      tday = tday < 10 ? "0" + tday : tday;
      tmonth = tmonth < 10 ? "0" + tmonth : tmonth;
      getWeekAgo = tyear + "-" + tmonth + "-" + tday;
      return getWeekAgo;
    }
  };

}).call(this);
