// Generated by CoffeeScript 1.7.1
(function() {
  var path, rootPath;

  path = require('path');
  
  rootPath = path.normalize(__dirname + '/..');

  module.exports = {
    development: {
      root: rootPath,
      app: {
        name: 'WorldFile'
      }
    },
    production: {
      root: rootPath,
      app: {
        name: 'WorldFile'
      }
    }
  };

}).call(this);
